spring:
  servlet:
    multipart:       #spring boot file upload size setting
      max-file-size: 10MB #max size of one file
      max-request-size: 30MB #max size of files to upload once
  sql:
    init.mode: never #operate sql script to all database

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB.USER}
    password: ${DB.PW}
    url: jdbc:mysql://${DB.HOST}:3306/diary?useSSL=false&serverTimezone=Asia/Seoul
  jpa:
    defer-datasource-initialization: true #data.sql operated before hibernate initialization "true"
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        default_batch_fetch_size: 100


#logging:
#  level:
#    org.springframework:
#      debug
